FROM golang:alpine

ARG GITHUB_BRANCH

RUN apk update && apk add git

RUN mkdir -p /go/src/github.com/byuoitav
ADD . /go/src/github.com/byuoitav/event-translator-microservice

WORKDIR /go/src/github.com/byuoitav/event-translator-microservice

RUN gvt fetch -branch ${GITHUB_BRANCH} github.com/byuoitav/event-router-microservice/eventinfrastructure

RUN go get -d -v
RUN go install -v

CMD ["/go/bin/event-translator-microservice"]

EXPOSE 7002
